  $(document).ready(function(){
	   $("#form5").validate({
		   rules:{
			   "user.userName":{
				   required:true,
				   minlength:6,
				   maxlength:10
			   },
			   "user.password":{
				   required:true,
				   minlength:6,
				   maxlength:16
			   }
		   },
		   messages:{
			   //这里的username是input中的name而不是id
			   "user.userName":{
				   required:"必须填写用户名",
				   minlength:"用户名最小为6位",
				   maxlength:"用户名最大为10位"
			   }, 
			   "user.password":{
				   required:"必须填写密码",
				   minlength:"密码最小为6位",
				   maxlength:"密码最大为12位"
			   } 
		   }
	   });
	   $("#form4").validate({
		   rules:{
			   "user.userName":{
				   required:true,
				   minlength:6,
				   maxlength:10
			   },
			   "user.password":{
				   required:true,
				   minlength:6,
				   maxlength:16
			   },
			   "password2":{
					  equalTo:"#pwd"
				   }
		   },
		   messages:{
			   //这里的username是input中的name而不是id
			   "user.userName":{
				   required:"必须填写用户名",
				   minlength:"用户名最小为6位",
				   maxlength:"用户名最大为10位"
			   }, 
			   "user.password":{
				   required:"必须填写密码",
				   minlength:"密码最小为6位",
				   maxlength:"密码最大为12位"
			   }, 
			   "password2":{
					  equalTo:"两次密码不一致"
				   }
		   }
	   });
   });